# Generated by Django 5.2.3 on 2025-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0003_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', null=True, upload_to='profile_photos/'),
        ),
    ]
