# Generated by Django 5.2.3 on 2025-06-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0004_passengerprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_tickets',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_infants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business')], default='ECONOMY', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='business_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='business_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
